# Generated by Django 3.0.6 on 2020-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20200528_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='access',
        ),
        migrations.AddField(
            model_name='note',
            name='access',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
